### ISSUE TITLE
图片好像不是最新的了

### ISSUE THREAD

**Issue by CyberFei** [zhuba-Ahhh/df-api#1]
有些图标都已经改掉了，这个数据里很多都是旧的

**Comment by zhuba-Ahhh** [comment]
s1赛季 v1版本，s2赛季在做了

**Comment by CyberFei** [comment]
OK，方便说下数据来源吗？游戏解包还是爬虫之类的

**Comment by zhuba-Ahhh** [comment]
> OK，方便说下数据来源吗？游戏解包还是爬虫之类的

charles和爬虫抓小程序包
